var lang = {
	'danh_muc':'Danh mục',
	'tinh_trang':'Tình trạng',
	'mau_sac':'Màu sắc',
	'kich_thuoc':'Kích thước',
	'chi_tiet':'Chi tiết',
	'so_luong':'Số lượng',
	'mua_ngay_voi_gia':'Mua ngay với giá',
	'dat_mua_giao_tan_noi':'Đặt mua giao hàng tận nơi',
	'ban_chua_nhap_tu_khoa':'Bạn chưa nhập từ khóa',
	'bo_ap_dung':'Bỏ áp dụng',
	'ap_dung':'Áp dụng',
	'chua_nhap_email':'Bạn chưa nhập email',
	'email_chua_dung_dinh_dang':'Định dạng mail chưa đúng',
	'chua_nhap_ho_ten':'Bạn chưa nhập họ tên',
	'chua_nhap_dien_thoai':'Bạn chưa nhập số điện thoại',
	'dinh_dang_dien_thoai':'Định dạng số điện thoại chưa đúng',
	'chua_nhap_noi_dung':'Bạn chưa nhập nội dung',
	'email_sai_dinh_dang':'Hãy nhập email đúng định dạng vd: example@gmail.com',
	'dien_thoai_sai_dinh_dang':'Số điện thoại chưa đúng định dạng vd: 0903911082',
	'chua_nhap_mat_khau':'Bạn chưa nhập mật khẩu',
	'mat_khau_khong_dung_dinh_dang':'Phải chứa ít nhất một số và một chữ hoa và chữ thường và ít nhất 8 ký tự trở lên',
	'chua_nhap_mat_khau_xac_nhan':'Bạn chưa nhập mật khẩu xác nhận',
	'mat_khau_khong_trung':'Mật khẩu xác nhận phải trùng với mật khẩu đã nhập',
	'chua_nhap_dia_chi':'Bạn chưa nhập địa chỉ',
	'chua_nhap_mat_khau_cu':'Bạn chưa nhập mật khẩu cũ',
	'chua_chon_tinh_thanh':'Bạn chưa chọn tỉnh thành',
	'chua_chon_quan_huyen':'Bạn chưa chọn quận huyện',
	'chua_chon_phuong_xa':'Bạn chưa chọn phường xã',
	'khong_co_du_lieu_trong_bang':'không có dữ liệu trong bảng',
	'bat_dau':'Bắt đầu',
	'den':'đến',
	'cua':'của',
	'hien_thi':'Hiển thị',
	'muc':'mục',
	'duoc_loc_tu':'được lọc từ',
	'tong_so_muc':'tổng số mục',
	'dau':'Đầu',
	'cuoi':'Cuối',
	'truoc':'Trước',
	'sau':'Sau',
	'search':'Tìm kiếm',
	'khong_tim_thay_ket_qua':'Không tìm thấy kết quả',
	'kich_hoat_cot_tang_dan':'kích hoạt để sắp xếp cột tăng dần',
	'kich_hoat_cot_giam_dan':'kích hoạt để sắp xếp cột giam dần'
	
};