var lang = {
	'list_muc': 'Category',
	'tinh_trang': 'Status',
	'mau_sac': 'Colors',
	'size_thuoc': 'Size',
	'chi_tiet': 'Details',
	'so_luong': 'Quantity',
	'buy_gay_voi_gia': 'Buy now for a price',
	'dat_mua_giao_tan_noi': 'Order delivery',
	'ban_chua_nhap_tu_khoa': 'You haven\'t entered keywords yet',
	'bo_ap_dung': 'Un-apply',
	'ap_dung': 'Apply',
	'chua_nhap_email': 'You have not entered your email',
	'email_chua_dung_dinh_dang': 'The email format is incorrect',
	'chua_nhap_ho_ten': 'You have not entered a full name',
	'chua_nhap_dien_thoai': 'You have not entered your phone number',
	'dinh_dang_dien_thoai': 'The phone number format is not correct',
	'chua_nhap_noi_dung': 'You have not entered any text',
	'email_sai_dinh_dang': 'Please enter your email in the correct format eg: example@gmail.com',
	'dien_thoai_sai_dinh_dang': 'The phone number is not in the correct format eg: 0903911082',
	'chua_nhap_mat_khau': 'You have not entered your password',
	'mat_khau_khong_dung_dinh_dang': 'Must contain at least one number and one uppercase and lowercase letters and at least 8 characters or more',
	'chua_nhap_mat_khau_xac_nhan': 'You have not entered a confirmation password',
	'mat_khau_khong_trung': 'The confirmation password must match the password entered',
	'chua_nhap_dia_chi': 'You did not enter an address',
	'chua_nhap_mat_khau_cu': 'You have not entered your old password',
	'chua_chon_tinh_thanh': 'You have not selected a province',
	'chua_chon_quan_huyen': 'You have not selected a district',
	'chua_chon_phuong_xa': 'You haven\'t selected a commune yet',
	'khong_co_du_lieu_trong_bang': 'There is no data in the table',
	'bat_dau': 'Get started',
	'den': 'to',
	'cua': 'of',
	'hien_thi': 'Display',
	'muc': 'section',
	'duoc_loc_tu': 'filtered from',
	'tong_so_muc': 'total items',
	'dau': 'First',
	'cuoi': 'Last',
	'before': 'Before',
	'after': 'After',
	'search': 'Search',
	'khong_tim_thay_ket_qua': 'No results found',
	'kich_hoat_cot_tang_dan': 'activate for ascending column sorting',
	'kich_hoat_cot_giam_dan': 'activate for descending column sorting'
};